import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Map, Calendar, ArrowRight, TrendingUp, BarChart3, Info, CheckCircle2, Download, FileText } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { useLanguage } from '../../context/LanguageContext';

const crops = ['Wheat', 'Rice', 'Cotton', 'Sugarcane', 'Maize'];
const soilTypes = ['Alluvial', 'Black', 'Red', 'Laterite', 'Loamy'];

const YieldPrediction = () => {
    const { t } = useLanguage();
    const [formData, setFormData] = useState({
        cropType: 'Wheat',
        area: '',
        soilType: 'Loamy',
        season: 'Rabi'
    });
    const [calculating, setCalculating] = useState(false);
    const [result, setResult] = useState(null);

    const handleCalculate = (e) => {
        e.preventDefault();
        setCalculating(true);
        setResult(null);

        // Mock AI Calculation delay
        setTimeout(() => {
            const areaNum = parseFloat(formData.area) || 1;
            const yieldPerHectare = formData.cropType === 'Wheat' ? 3.5 : 4.2;
            const estimatedYield = (areaNum * yieldPerHectare).toFixed(1);
            const msp = formData.cropType === 'Wheat' ? 2125 : 2040;
            const revenue = (estimatedYield * 10 * msp).toLocaleString(); // 1 quintal = 100kg, harvest in tons? let's assume tons

            setResult({
                estimated_yield: estimatedYield,
                unit: 'Tons',
                potential_revenue: revenue,
                efficiency: 'High',
                tips: [
                    "Increase Nitrogen by 10% for better grain filling.",
                    "Schedule next irrigation in 12 days.",
                    "Monitor for Aphids in the lower leaves."
                ]
            });
            setCalculating(false);
        }, 2000);
    };

    const generatePDF = () => {
        if (!result) return;

        const doc = new jsPDF();
        const timestamp = new Date().toLocaleString();

        // Header
        doc.setFillColor(16, 185, 129); // Primary Green
        doc.rect(0, 0, 210, 40, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.text('Farm Predict - Yield Report', 20, 25);
        
        // Content
        doc.setTextColor(31, 41, 55); // Text Color
        doc.setFontSize(12);
        doc.text(`Generated on: ${timestamp}`, 20, 50);
        
        doc.setFontSize(16);
        doc.text('Prediction Details', 20, 65);
        doc.setFontSize(12);
        doc.text(`Crop Type: ${formData.cropType}`, 30, 75);
        doc.text(`Land Area: ${formData.area} Acres`, 30, 85);
        doc.text(`Soil Type: ${formData.soilType}`, 30, 95);
        doc.text(`Season: ${formData.season}`, 30, 105);

        doc.setDrawColor(226, 232, 240);
        doc.line(20, 115, 190, 115);

        doc.setFontSize(16);
        doc.text('AI Prediction Results', 20, 130);
        doc.setFontSize(14);
        doc.setTextColor(16, 185, 129);
        doc.text(`Estimated Yield: ${result.estimated_yield} ${result.unit}`, 30, 140);
        doc.text(`Potential Revenue: ₹${result.potential_revenue}`, 30, 150);
        
        doc.setTextColor(31, 41, 55);
        doc.setFontSize(16);
        doc.text('Farming Strategies', 20, 165);
        doc.setFontSize(11);
        result.tips.forEach((tip, index) => {
            doc.text(`- ${tip}`, 30, 175 + (index * 10));
        });

        doc.setFontSize(10);
        doc.setTextColor(156, 163, 175);
        doc.text('This report is generated by Farm Predict AI. Professional consultation is recommended.', 20, 280);

        doc.save(`FarmPredict_Report_${formData.cropType}_${new Date().getTime()}.pdf`);
    };

    return (
        <div className="max-w-6xl mx-auto pb-12">
            <header className="mb-8">
                <h1 className="text-3xl font-bold text-darkSlate font-['Outfit'] mb-2">{t('yieldTitle')}</h1>
                <p className="text-slate-500 font-medium">{t('yieldDesc')}</p>
            </header>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                {/* Form Section */}
                <div className="lg:col-span-12 xl:col-span-5 bg-white p-8 rounded-3xl border border-slate-100 shadow-sm h-fit">
                    <form onSubmit={handleCalculate} className="space-y-6">
                        <div>
                            <label className="block text-sm font-bold text-slate-700 mb-3 flex items-center gap-2">
                                <Map size={18} className="text-emerald-500" /> {t('landArea')}
                            </label>
                            <input
                                type="number"
                                required
                                value={formData.area}
                                onChange={(e) => setFormData({ ...formData, area: e.target.value })}
                                placeholder="e.g., 2.5"
                                className="w-full px-5 py-3.5 bg-slate-50 border border-slate-200 rounded-2xl focus:ring-2 focus:ring-emerald-500 transition-all font-medium"
                            />
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-bold text-slate-700 mb-3">{t('cropType')}</label>
                                <select
                                    value={formData.cropType}
                                    onChange={(e) => setFormData({ ...formData, cropType: e.target.value })}
                                    className="w-full px-5 py-3.5 bg-slate-50 border border-slate-200 rounded-2xl focus:ring-2 focus:ring-emerald-500 transition-all font-medium"
                                >
                                    {crops.map(crop => <option key={crop} value={crop}>{crop}</option>)}
                                </select>
                            </div>
                            <div>
                                <label className="block text-sm font-bold text-slate-700 mb-3">{t('soilType')}</label>
                                <select
                                    value={formData.soilType}
                                    onChange={(e) => setFormData({ ...formData, soilType: e.target.value })}
                                    className="w-full px-5 py-3.5 bg-slate-50 border border-slate-200 rounded-2xl focus:ring-2 focus:ring-emerald-500 transition-all font-medium"
                                >
                                    {soilTypes.map(soil => <option key={soil} value={soil}>{soil}</option>)}
                                </select>
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-bold text-slate-700 mb-3 flex items-center gap-2">
                                <Calendar size={18} className="text-emerald-500" /> {t('croppingSeason')}
                            </label>
                            <div className="grid grid-cols-2 gap-3">
                                {['Kharif', 'Rabi'].map(season => (
                                    <button
                                        key={season}
                                        type="button"
                                        onClick={() => setFormData({ ...formData, season })}
                                        className={`py-3 rounded-xl font-bold transition-all border ${formData.season === season ? 'bg-emerald-600 border-emerald-600 text-white shadow-lg' : 'bg-slate-50 border-slate-200 text-slate-600 hover:border-emerald-200'}`}
                                    >
                                        {season}
                                    </button>
                                ))}
                            </div>
                        </div>

                        <button
                            type="submit"
                            disabled={calculating}
                            className={`w-full py-4 bg-emerald-600 text-white font-black rounded-2xl shadow-lg shadow-emerald-200 hover:bg-emerald-700 transition-all flex items-center justify-center gap-2 ${calculating ? 'opacity-70 cursor-not-allowed' : 'active:scale-95'}`}
                        >
                            {calculating ? (
                                <span className="flex items-center gap-2">
                                    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                                    {t('calculatingYield')}
                                </span>
                            ) : (
                                <>{t('calculateYield')} <ArrowRight size={20} /></>
                            )}
                        </button>
                    </form>
                </div>

                {/* Results Section */}
                <div className="lg:col-span-12 xl:col-span-7">
                    <AnimatePresence mode="wait">
                        {!result && !calculating && (
                            <motion.div
                                key="empty"
                                initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                                className="h-full min-h-[400px] border-2 border-dashed border-slate-200 rounded-3xl p-12 flex flex-col items-center justify-center text-center bg-slate-50/50"
                            >
                                <div className="w-20 h-20 bg-white rounded-3xl flex items-center justify-center mb-6 shadow-sm border border-slate-100">
                                    <TrendingUp size={40} className="text-slate-300" />
                                </div>
                                <h3 className="text-2xl font-bold text-slate-400 mb-2 font-['Outfit']">{t('awaitingParams')}</h3>
                                <p className="text-slate-500 font-medium max-w-[320px]">{t('awaitingParamsDesc')}</p>
                            </motion.div>
                        )}

                        {calculating && (
                            <motion.div
                                key="calc"
                                initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }}
                                className="h-full min-h-[400px] bg-white rounded-3xl border border-slate-100 p-12 flex flex-col items-center justify-center shadow-lg relative overflow-hidden"
                            >
                                <div className="absolute top-0 left-0 w-full h-1 bg-slate-100">
                                    <motion.div
                                        initial={{ width: 0 }} animate={{ width: "100%" }} transition={{ duration: 2 }}
                                        className="h-full bg-emerald-500"
                                    ></motion.div>
                                </div>
                                <div className="w-32 h-32 bg-emerald-50 rounded-full flex items-center justify-center mb-8 border-4 border-emerald-100">
                                    <motion.div animate={{ scale: [1, 1.1, 1] }} transition={{ repeat: Infinity, duration: 1.5 }}>
                                        <BarChart3 size={56} className="text-emerald-500" />
                                    </motion.div>
                                </div>
                                <h3 className="text-2xl font-bold text-darkSlate mb-4">{t('processingData')}</h3>
                                <p className="text-slate-500 font-medium text-center max-w-[300px]">{t('aiProcessingDesc')}</p>
                            </motion.div>
                        )}

                        {result && (
                            <motion.div
                                key="result"
                                initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}
                                className="space-y-6"
                            >
                                <div className="bg-white p-8 rounded-3xl border border-emerald-100 shadow-xl relative overflow-hidden">
                                    {/* Background Glow */}
                                    <div className="absolute -top-24 -right-24 w-64 h-64 bg-emerald-50 rounded-full blur-3xl opacity-60"></div>

                                    <div className="relative z-10">
                                        <div className="flex justify-between items-center mb-8">
                                            <div className="px-4 py-1.5 bg-emerald-100 text-emerald-700 rounded-full text-xs font-black uppercase tracking-widest">{t('yieldResult')}</div>
                                            <div className="flex items-center gap-2 text-slate-400 font-bold text-sm">
                                                <Info size={16} /> {t('dataUpdated')} 1 {t('minAgo')}
                                            </div>
                                        </div>

                                        <div className="flex flex-col md:flex-row gap-8 items-end mb-10">
                                            <div className="flex-1">
                                                <p className="text-slate-500 font-bold mb-2 uppercase tracking-tight text-sm">{t('estHarvest')}</p>
                                                <div className="flex items-baseline gap-4">
                                                    <h2 className="text-7xl font-black text-darkSlate font-['Outfit'] tracking-tighter">
                                                        {result.estimated_yield}
                                                    </h2>
                                                    <span className="text-3xl font-black text-emerald-600 font-['Outfit']">{result.unit}</span>
                                                </div>
                                            </div>
                                            <div className="p-6 bg-slate-50 rounded-2xl border border-slate-100 min-w-[200px]">
                                                <p className="text-slate-400 text-xs font-bold uppercase mb-1">{t('potentialValue')}</p>
                                                <p className="text-2xl font-black text-darkSlate">₹{result.potential_revenue}</p>
                                                <p className="text-emerald-600 text-xs font-bold">{t('estMSP')}</p>
                                            </div>
                                        </div>

                                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-8 border-t border-slate-100">
                                            <div>
                                                <p className="text-slate-400 text-xs font-bold uppercase mb-2">{t('efficiencyScore')}</p>
                                                <div className="flex items-center gap-3">
                                                    <div className="w-10 h-10 bg-blue-50 text-blue-600 rounded-xl flex items-center justify-center font-bold">A+</div>
                                                    <span className="text-lg font-black text-slate-700">{result.efficiency}</span>
                                                </div>
                                            </div>
                                            <div className="md:col-span-2">
                                                <p className="text-slate-400 text-xs font-bold uppercase mb-3">{t('maxStrategy')}</p>
                                                <div className="space-y-3">
                                                    {result.tips.map((tip, i) => (
                                                        <div key={i} className="flex items-start gap-3 text-sm text-slate-600 font-medium">
                                                            <CheckCircle2 size={16} className="text-emerald-500 mt-0.5" /> {tip}
                                                        </div>
                                                    ))}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div className="bg-gradient-to-r from-emerald-600 to-emerald-800 p-1 rounded-3xl shadow-lg">
                                    <div className="bg-emerald-900/10 p-6 rounded-[calc(1.5rem-4px)] flex justify-between items-center text-white">
                                        <div>
                                            <h4 className="font-bold text-lg">{t('exportReport')}</h4>
                                            <p className="text-emerald-100/70 text-sm">{t('downloadPDF')}</p>
                                        </div>
                                        <button 
                                            onClick={generatePDF}
                                            className="px-6 py-3 bg-white text-emerald-800 font-bold rounded-xl hover:bg-emerald-50 transition-all flex items-center gap-2"
                                        >
                                            <Download size={20} /> {t('downloadPDF')}
                                        </button>
                                    </div>
                                </div>
                            </motion.div>
                        )}
                    </AnimatePresence>
                </div>
            </div>
        </div>
    );
};

export default YieldPrediction;
