import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    English: {
        welcome: "Welcome back",
        overview: "Here is your farming overview for today.",
        currentWeather: "Current Weather",
        recommendedCrop: "Recommended Crop",
        soilMoisture: "Soil Moisture",
        marketPrice: "Market Price",
        quickActions: "Quick Actions",
        newSeason: "New Planting Season?",
        predictNow: "Predict Best Crop Now",
        home: "Dashboard",
        cropRec: "Crop Recommendation",
        diseaseDet: "Disease Detection",
        weather: "Weather Insights",
        yield: "Yield Prediction",
        irrigation: "Irrigation Planner",
        market: "Market Prices",
        alerts: "Disease Alerts",
        history: "Prediction History",
        profile: "Profile",
        logout: "Logout",
        healthScore: "Farm Health Score",
        sustainability: "Sustainability Index",
        analysisHistory: "Analysis History",
        historyDesc: "Access and review all your previous AI crop recommendations.",
        searchCrop: "Search by crop...",
        viewReport: "View Report",
        downloadReport: "Download PDF",
        reportTitle: "Agriculture Analysis Report",
        farmPredictAI: "Farm Predict AI Intelligence",
        confidence: "AI Confidence",
        soilParams: "Soil Parameters",
        weatherEnv: "Weather & Environment",
        nitrogen: "Nitrogen (N)",
        phosphorus: "Phosphorus (P)",
        potassium: "Potassium (K)",
        ph: "Soil pH",
        temp: "Temperature (°C)",
        humidity: "Humidity (%)",
        rainfall: "Rainfall (mm)",
        predictCrop: "Predict Best Crop",
        analyzing: "Analyzing Data with AI...",
        awaitingParams: "Awaiting Parameters",
        awaitingDesc: "Enter your field's soil and weather data and click predict to see the AI's recommendation here.",
        analysisComplete: "Analysis Complete",
        suitableCond: "Suitable Conditions",
        fertilizerTips: "Fertilizer Tips",
        estimatedYield: "Estimated Yield",
        runNew: "Run New Prediction",
        diseaseDetDesc: "Upload a photo of the affected crop part for AI analysis.",
        dropImage: "Drop your image here",
        selectImage: "Select Image",
        analyzePlant: "Analyze Plant Health",
        scanningLeaf: "Scanning Leaf Patterns",
        neuralNetwork: "AI is identifying pathogen signatures...",
        detectedCondition: "Detected Condition",
        severityLabel: "Severity",
        aboutDisease: "About this Disease",
        preventionSteps: "Prevention Steps",
        recTreatment: "Recommended Treatment",
        scanAnother: "Scan Another Image",
        weatherIntel: "Weather Intelligence",
        weatherIntelDesc: "Real-time climate analysis and agricultural weather forecasting.",
        soilEnv: "Soil Environment",
        moisture: "Moisture",
        soilTemp: "Soil Temp",
        tempTrend: "Temperature Trend",
        rainfallProb: "Rainfall Probability",
        uvIndexLabel: "High UV Index Today",
        today: "Today",
        windLabel: "Wind",
        farmHealthOptimal: "Your farm health is optimal. Soil nitrogen is slightly low but moisture levels are perfect for wheat.",
        yellowRustAlert: "Yellow Rust detected within 15km",
        protectCrops: "Protect your wheat crops now.",
        heatwaveAdvisory: "Heatwave advisory issued",
        increaseIrrigation: "Increase irrigation frequency by 20%.",
        newSeasonQ: "New Planting Season?",
        newSeasonDesc: "Run our AI-powered Crop Recommendation model to find the most profitable crop based on your exact conditions.",
        predictBestCrop: "Predict Best Crop Now",
        checkedMarketPrice: "Checked Market Price",
        wheatPriceIncreased: "Wheat prices increased by ₹150",
        ranCropPred: "Ran Crop Prediction",
        cottonMatch: "Recommended: Cotton (88% match)",
        weatherAlert: "Weather Alert",
        heavyRainfall: "Heavy rainfall expected tomorrow",
        regionalDiseaseRisks: "Regional Disease Risks",
        criticalAlerts: "Critical Alerts Nearby",
        recentHistory: "Recent History",
        viewAll: "View All",
        aiInsight: "AI Insight",
        applyUrea: "Apply Urea in the next 48 hours for maximum yield uptake.",
        climateIntel: "Climate Intelligence",
        tempRainMonitor: "Temperature & Rainfall Monitoring",
        optimalForSeason: "Optimal for current season",
        precisionSensorData: "Precision sensor data",
        trackLiveTrends: "Track live trends",
        govtSchemes: "Govt Schemes",
        schemesTitle: "Government Schemes & Subsidies",
        schemesDesc: "Discover and apply for center and state-sponsored programs designed to support your agricultural growth and financial stability.",
        searchSchemes: "Search for schemes, keywords, or benefits...",
        allCategories: "All Categories",
        keyBenefit: "Key Benefit",
        eligibility: "Eligibility",
        viewDetails: "View Details & Apply",
        noSchemes: "No schemes found",
        adjustSearch: "Try adjusting your search or filters.",
        activeStatus: "Active",
        yieldTitle: "Yield Estimation",
        yieldDesc: "Predict your harvest output based on field parameters and historical trends.",
        landArea: "Land Area (in Hectares)",
        cropType: "Crop Type",
        soilType: "Soil Type",
        croppingSeason: "Cropping Season",
        calculateYield: "Analyze Yield Potential",
        calculatingYield: "Calculating Yield...",
        processingData: "Processing Historical Data",
        aiProcessingDesc: "Our AI is correlating your parameters with regional yield benchmarks...",
        awaitingYieldParams: "Awaiting Parameters",
        awaitingParamsDesc: "Fill in your field details and analyze the estimated harvest yield.",
        yieldResult: "Prediction Result",
        estHarvest: "Estimated Total Harvest",
        potentialValue: "Potential Value",
        estMSP: "Estimated @ current MSP",
        efficiencyScore: "Efficiency Score",
        maxStrategy: "Maximization Strategy",
        exportReport: "Export Report",
        downloadPDF: "Download PDF",
        dataUpdated: "Data updated",
        minAgo: "min ago",
        irrigationTitle: "Smart Irrigation Planner",
        irrigationDesc: "Precision watering based on AI soil-moisture analysis and evaporation rates.",
        nextWatering: "Next Scheduled Event",
        targetVolume: "Target Volume",
        systemOnline: "System Status: Online",
        evaporation: "Evaporation",
        windSpeed: "Wind Speed",
        automation: "Automation",
        manualOverride: "Manual Override Start",
        upcomingSchedule: "Upcoming Schedule",
        lowRainWarning: "Low Rainfall Warning",
        rainAdjustDesc: "Schedule adjusted: +15% volume required next week.",
        pumpEfficiency: "Pump Efficiency",
        maintenanceDue: "Maintenance due in",
        days: "days",
        marketTitle: "Market Price Intelligence",
        marketDesc: "Live Mandi prices and futures trends for your crops.",
        priceAlerts: "Price Alerts",
        mandiTrend: "Mandi Price Trend",
        perQuintal: "Per Quintal (100kg)",
        marketSearch: "Market Search",
        searchCommodity: "Search commodity...",
        topTrending: "Top Trending",
        noResults: "No results found.",
        exportPotential: "Export Potential",
        organicCottonDemand: "International demand for Organic Cotton is up by 15%. Consider certification to increase your ROI.",
        readInsights: "Read Insights",
        diseaseTitle: "AI Disease Detection",
        diseaseDesc: "Scan your crop for early signs of pests, fungus, or nutrient deficiencies.",
        selectCropDet: "Select Crop for Analysis",
        uploadPhoto: "Upload Photo",
        uploadDesc: "Take a clear picture of the affected leaf or stem.",
        analyzingDisease: "Analyzing Sample...",
        aiScanning: "AI scanning for 40+ common crop pathogens...",
        awaitingUpload: "Awaiting Image",
        awaitingUploadDesc: "Upload or take a photo of your crop to start the AI diagnostic process.",
        diagnosis: "AI Diagnosis",
        confidenceDisease: "Confidence",
        treatment: "Recommended Treatment",
        prevention: "Prevention Tip",
        bookConsult: "Book Specialist Consultation",
        alertsTitle: "Recent Disease Alerts",
        alertsDesc: "Regional outbreak notifications and preventive advisories.",
        riskLevel: "Risk Level",
        affectedCrops: "Affected Crops",
        advisory: "Advisory",
        saveChanges: "Save Changes",
        applyNow: "Apply Now"
    },
    Hindi: {
        welcome: "आपका स्वागत है",
        overview: "यहाँ आज के लिए आपका खेती का अवलोकन है।",
        currentWeather: "वर्तमान मौसम",
        recommendedCrop: "अनुशंसित फसल",
        soilMoisture: "मिट्टी की नमी",
        marketPrice: "बाजार मूल्य",
        quickActions: "त्वरित कार्रवाई",
        newSeason: "नया बुवाई का मौसम?",
        predictNow: "अभी सर्वोत्तम फसल की भविष्यवाणी करें",
        home: "डैशबोर्ड",
        cropRec: "फसल सिफारिश",
        diseaseDet: "रोग पहचान",
        weather: "मौसम की जानकारी",
        yield: "उपज भविष्यवाणी",
        irrigation: "सिंचाई योजना",
        market: "बाजार भाव",
        alerts: "रोग अलर्ट",
        history: "भविष्यवाणी इतिहास",
        profile: "प्रोफाइल",
        logout: "लॉगआउट",
        healthScore: "फार्म स्वास्थ्य स्कोर",
        sustainability: "स्थिरता सूचकांक",
        analysisHistory: "विश्लेषण इतिहास",
        historyDesc: "अपनी पिछली सभी AI फसल सिफारिशों को देखें और समीक्षा करें।",
        searchCrop: "फसल के द्वारा खोजें...",
        viewReport: "रिपोर्ट देखें",
        downloadReport: "पीडीएफ डाउनलोड करें",
        reportTitle: "कृषि विश्लेषण रिपोर्ट",
        farmPredictAI: "फार्म प्रेडिक्ट AI इंटेलिजेंस",
        confidence: "AI आत्मविश्वास",
        soilParams: "मिट्टी के पैरामीटर",
        weatherEnv: "मौसम और पर्यावरण",
        nitrogen: "नाइट्रोजन (N)",
        phosphorus: "फास्फोरस (P)",
        potassium: "पोटेशियम (K)",
        ph: "मिट्टी का पीएच",
        temp: "तापमान (°C)",
        humidity: "नमी (%)",
        rainfall: "वर्षा (mm)",
        predictCrop: "सर्वोत्तम फसल की भविष्यवाणी करें",
        analyzing: "एआई के साथ डेटा का विश्लेषण...",
        awaitingParams: "मापदंडों की प्रतीक्षा है",
        awaitingDesc: "अपने क्षेत्र की मिट्टी और मौसम का डेटा दर्ज करें और यहां एआई की सिफारिश देखने के लिए भविष्यवाणी पर क्लिक करें।",
        analysisComplete: "विश्लेषण पूरा हुआ",
        suitableCond: "उपयुक्त स्थितियां",
        fertilizerTips: "उर्वरक सुझाव",
        estimatedYield: "अनुमानित उपज",
        runNew: "नई भविष्यवाणी चलाएं",
        diseaseDetDesc: "एआई विश्लेषण के लिए प्रभावित फसल के हिस्से का फोटो अपलोड करें।",
        dropImage: "अपनी छवि यहाँ छोड़ें",
        selectImage: "छवि चुनें",
        analyzePlant: "पौधों के स्वास्थ्य का विश्लेषण करें",
        scanningLeaf: "पत्ती के पैटर्न को स्कैन किया जा रहा है",
        neuralNetwork: "एआई रोग के लक्षणों की पहचान कर रहा है...",
        detectedCondition: "पहचानी गई स्थिति",
        severityLabel: "गंभीरता",
        aboutDisease: "इस बीमारी के बारे में",
        preventionSteps: "रोकथाम के कदम",
        recTreatment: "अनुशंसित उपचार",
        scanAnother: "दूसरी छवि स्कैन करें",
        weatherIntel: "मौसम की जानकारी",
        weatherIntelDesc: "वास्तविक समय जलवायु विश्लेषण और कृषि मौसम पूर्वानुमान।",
        soilEnv: "मिट्टी का वातावरण",
        moisture: "नमी",
        soilTemp: "मिट्टी का तापमान",
        tempTrend: "तापमान का रुझान",
        rainfallProb: "वर्षा की संभावना",
        uvIndexLabel: "आज उच्च यूवी इंडेक्स",
        today: "आज",
        windLabel: "हवा",
        farmHealthOptimal: "आपके खेत का स्वास्थ्य इष्टतम है। मिट्टी में नाइट्रोजन थोड़ा कम है लेकिन नमी का स्तर गेहूं के लिए उपयुक्त है।",
        yellowRustAlert: "15 किमी के भीतर पीला रतुआ (Yellow Rust) पाया गया",
        protectCrops: "अपनी गेहूं की फसल को अभी बचाएं।",
        heatwaveAdvisory: "लू (Heatwave) की चेतावनी जारी",
        increaseIrrigation: "सिंचाई की आवृत्ति 20% बढ़ाएं।",
        newSeasonQ: "नया बुवाई का मौसम?",
        newSeasonDesc: "आपकी सटीक स्थितियों के आधार पर सबसे लाभदायक फसल खोजने के लिए हमारे एआई-संचालित फसल सिफारिश मॉडल को चलाएं।",
        predictBestCrop: "अभी सर्वोत्तम फसल की भविष्यवाणी करें",
        checkedMarketPrice: "बाजार मूल्य की जाँच की",
        wheatPriceIncreased: "गेहूं की कीमतों में ₹150 की वृद्धि हुई",
        ranCropPred: "फसल भविष्यवाणी चलाई गई",
        cottonMatch: "अनुशंसित: कपास (88% मिलान)",
        weatherAlert: "मौसम की चेतावनी",
        heavyRainfall: "कल भारी बारिश होने की संभावना है",
        regionalDiseaseRisks: "क्षेत्रीय रोग जोखिम",
        criticalAlerts: "पास में महत्वपूर्ण अलर्ट",
        recentHistory: "हाल का इतिहास",
        viewAll: "सभी देखें",
        aiInsight: "एआई अंतर्दृष्टि",
        applyUrea: "अधिकतम उपज के लिए अगले 48 घंटों में यूरिया डालें।",
        climateIntel: "जलवायु खुफिया जानकारी",
        tempRainMonitor: "तापमान और वर्षा की निगरानी",
        optimalForSeason: "वर्तमान मौसम के लिए इष्टतम",
        precisionSensorData: "सटीक सेंसर डेटा",
        trackLiveTrends: "लाइव रुझानों को ट्रैक करें",
        govtSchemes: "सरकारी योजनाएं",
        schemesTitle: "सरकारी योजनाएं और सब्सिडी",
        schemesDesc: "अपने कृषि विकास और वित्तीय स्थिरता का समर्थन करने के लिए डिज़ाइन किए गए केंद्र और राज्य प्रायोजित कार्यक्रमों को खोजें और उनके लिए आवेदन करें।",
        searchSchemes: "योजनाओं, कीवर्ड या लाभों के लिए खोजें...",
        allCategories: "सभी श्रेणियां",
        keyBenefit: "प्रमुख लाभ",
        eligibility: "पात्रता",
        viewDetails: "विवरण देखें और आवेदन करें",
        noSchemes: "कोई योजना नहीं मिली",
        adjustSearch: "अपनी खोज या फ़िल्टर समायोजित करने का प्रयास करें।",
        activeStatus: "सक्रिय",
        yieldTitle: "उपज का अनुमान",
        yieldDesc: "क्षेत्र के मापदंडों और ऐतिहासिक रुझानों के आधार पर अपने फसल उत्पादन की भविष्यवाणी करें।",
        landArea: "भूमि क्षेत्र (हेक्टेयर में)",
        cropType: "फसल का प्रकार",
        soilType: "मिट्टी का प्रकार",
        croppingSeason: "फसल का मौसम",
        calculateYield: "उपज क्षमता का विश्लेषण करें",
        calculatingYield: "उपज की गणना हो रही है...",
        processingData: "ऐतिहासिक डेटा को प्रोसेस किया जा रहा है",
        aiProcessingDesc: "हमारा AI आपके मापदंडों को क्षेत्रीय उपज बेंचमार्किंग के साथ सहसंबंधित कर रहा है...",
        awaitingYieldParams: "मापदंडों की प्रतीक्षा है",
        awaitingParamsDesc: "अपने क्षेत्र का विवरण भरें और अनुमानित फसल उपज का विश्लेषण करें।",
        yieldResult: "भविष्यवाणी परिणाम",
        estHarvest: "अनुमानित कुल फसल",
        potentialValue: "संभावित मूल्य",
        estMSP: "वर्तमान MSP पर अनुमानित",
        efficiencyScore: "दक्षता स्कोर",
        maxStrategy: "अधिकतम रणनीति",
        exportReport: "रिपोर्ट निर्यात करें",
        downloadPDF: "PDF डाउनलोड करें",
        dataUpdated: "डेटा अपडेट किया गया",
        minAgo: "मिनट पहले",
        irrigationTitle: "स्मार्ट सिंचाई योजनाकार",
        irrigationDesc: "AI मृदा-नमी विश्लेषण और वाष्पीकरण दरों के आधार पर सटीक पानी देना।",
        nextWatering: "अगला अनुसूचित कार्यक्रम",
        targetVolume: "लक्ष्य मात्रा",
        systemOnline: "सिस्टम की स्थिति: ऑनलाइन",
        evaporation: "वाष्पीकरण",
        windSpeed: "हवा की गति",
        automation: "स्वचालन",
        manualOverride: "मैनुअल ओवरराइड प्रारंभ करें",
        upcomingSchedule: "आगामी कार्यक्रम",
        lowRainWarning: "कम वर्षा की चेतावनी",
        rainAdjustDesc: "शिड्यूल समायोजित: अगले सप्ताह 15% अधिक मात्रा की आवश्यकता है।",
        pumpEfficiency: "पंप दक्षता",
        maintenanceDue: "रखरखाव देय है",
        days: "दिनों में",
        marketTitle: "बाजार मूल्य खुफिया जानकारी",
        marketDesc: "आपकी फसलों के लिए लाइव मंडी की कीमतें और वायदा रुझान।",
        priceAlerts: "मूल्य अलर्ट",
        mandiTrend: "मंडी मूल्य रुझान",
        perQuintal: "प्रति क्विंटल (100 किलो)",
        marketSearch: "बाजार खोज",
        searchCommodity: "वस्तु खोजें...",
        topTrending: "शीर्ष रुझान",
        noResults: "कोई परिणाम नहीं मिला।",
        exportPotential: "निर्यात क्षमता",
        organicCottonDemand: "जैविक कपास की अंतर्राष्ट्रीय मांग में 15% की वृद्धि हुई है। अपना ROI बढ़ाने के लिए प्रमाणीकरण पर विचार करें।",
        readInsights: "अंतर्दृष्टि पढ़ें",
        diseaseTitle: "AI रोग पहचान",
        diseaseDesc: "कीटों, कवक या पोषक तत्वों की कमी के शुरुआती संकेतों के लिए अपनी फसल को स्कैन करें।",
        selectCropDet: "विश्लेषण के लिए फसल चुनें",
        uploadPhoto: "फोटो अपलोड करें",
        uploadDesc: "प्रभावित पत्ती या तने की स्पष्ट तस्वीर लें।",
        analyzingDisease: "नमूने का विश्लेषण हो रहा है...",
        aiScanning: "40+ सामान्य फसल रोगजनकों के लिए AI स्कैनिंग...",
        awaitingUpload: "छवि की प्रतीक्षा है",
        awaitingUploadDesc: "AI नैदानिक प्रक्रिया शुरू करने के लिए अपनी फसल का फोटो अपलोड करें या लें।",
        diagnosis: "AI निदान",
        confidenceDisease: "विश्वास",
        treatment: "अनुशंसित उपचार",
        prevention: "रोकथाम टिप",
        bookConsult: "विशेषज्ञ परामर्श बुक करें",
        alertsTitle: "हालिया रोग अलर्ट",
        alertsDesc: "क्षेत्रीय बीमारी के प्रकोप की सूचनाएं और निवारक सलाह।",
        riskLevel: "जोखिम स्तर",
        affectedCrops: "प्रभावित फसलें",
        advisory: "सलाह",
        saveChanges: "बदलाव सहेजें",
        applyNow: "अभी आवेदन करें"
    },
    Telugu: {
        welcome: "స్వాగతం",
        overview: "ఈరోజు మీ వ్యవసాయ అవలోకనం ఇక్కడ ఉంది.",
        currentWeather: "ప్రస్తుత వాతావరణం",
        recommendedCrop: "సిఫార్సు చేయబడిన పంట",
        soilMoisture: "నేల తేమ",
        marketPrice: "మార్కెట్ ధర",
        quickActions: "త్వరిత చర్యలు",
        newSeason: "కొత్త విత్తే కాలమా?",
        predictNow: "ఇప్పుడే ఉత్తమ పంటను అంచనా వేయండి",
        home: "డ్యాష్‌బోర్డ్",
        cropRec: "పంట సిఫార్సు",
        diseaseDet: "వ్యాధి గుర్తింపు",
        weather: "వాతావరణ సమాచారం",
        yield: "దిగుబడి అంచనా",
        irrigation: "నీటి పారుదల ప్రణాళిక",
        market: "మార్కెట్ ధరలు",
        alerts: "వ్యాధి హెచ్చరికలు",
        history: "అంచనా చరిత్ర",
        profile: "ప్రొఫైల్",
        logout: "లాగ్అవుట్",
        healthScore: "ఫామ్ హెల్త్ స్కోర్",
        sustainability: "సస్టైనబిలిటీ ఇండెక్స్",
        analysisHistory: "విశ్లేషణ చరిత్ర",
        historyDesc: "మీ మునుపటి AI పంట సిఫార్సులన్నింటినీ యాక్సెస్ చేయండి మరియు సమీక్షించండి.",
        searchCrop: "పంట ద్వారా వెతకండి...",
        viewReport: "నివేదికను చూడండి",
        downloadReport: "PDF డౌన్‌లోడ్ చేయండి",
        reportTitle: "వ్యవసాయ విశ్లేషణ నివేదిక",
        farmPredictAI: "ఫామ్ ప్రెడిక్ట్ AI ఇంటెలిజెన్స్",
        confidence: "AI విశ్వాసం",
        soilParams: "నేల పారామితులు",
        weatherEnv: "వాతావరణం & పర్యావరణం",
        nitrogen: "నత్రజని (N)",
        phosphorus: "భాస్వరం (P)",
        potassium: "పొటాషియం (K)",
        ph: "నేల pH",
        temp: "ఉష్ణోగ్రత (°C)",
        humidity: "తేమ (%)",
        rainfall: "వర్షపాతం (mm)",
        predictCrop: "ఉత్తమ పంటను అంచనా వేయండి",
        analyzing: "AIతో డేటాను విశ్లేషిస్తోంది...",
        awaitingParams: "పారామితుల కోసం వేచి ఉంది",
        awaitingDesc: "మీ పొలం నేల మరియు వాతావరణ డేటాను నమోదు చేయండి మరియు ఇక్కడ AI సిఫార్సును చూడటానికి నివేదిక బటన్ క్లిక్ చేయండి.",
        analysisComplete: "విశ్లేషణ పూర్తయింది",
        suitableCond: "అనువైన పరిస్థితులు",
        fertilizerTips: "ఎరువుల చిట్కాలు",
        estimatedYield: "అంచనా దిగుబడి",
        runNew: "కొత్త అంచనాను అమలు చేయండి",
        diseaseDetDesc: "AI విశ్లేషణ కోసం ప్రభావిత పంట భాగం యొక్క ఫోటోను అప్‌లోడ్ చేయండి.",
        dropImage: "మీ చిత్రాన్ని ఇక్కడ వేయండి",
        selectImage: "చిత్రాన్ని ఎంచుకోండి",
        analyzePlant: "మొక్కల ఆరోగ్యాన్ని విశ్లేషించండి",
        scanningLeaf: "ఆకు నమూనాలను స్కాన్ చేస్తోంది",
        neuralNetwork: "AI వ్యాధి లక్షణాలను గుర్తిస్తోంది...",
        detectedCondition: "గుర్తించిన పరిస్థితి",
        severityLabel: "తీవ్రత",
        aboutDisease: "ఈ వ్యాధి గురించి",
        preventionSteps: "నివారణ చర్యలు",
        recTreatment: "సిఫార్సు చేసిన చికిత్స",
        scanAnother: "మరో చిత్రాన్ని స్కాన్ చేయండి",
        weatherIntel: "వాతావరణ సమాచారం",
        weatherIntelDesc: "నిజ-సమయ వాతావరణ విశ్లేషణ మరియు వ్యవసాయ వాతావరణ సూచన.",
        soilEnv: "నేల వాతావరణం",
        moisture: "తేమ",
        soilTemp: "నేల ఉష్ణోగ్రత",
        tempTrend: "ఉష్ణోగ్రత ధోరణి",
        rainfallProb: "వర్షపాతం సంభావ్యత",
        uvIndexLabel: "ఈరోజు అధిక UV ఇండెక్స్",
        today: "నేడు",
        windLabel: "గాలి",
        farmHealthOptimal: "మీ పొలం ఆరోగ్యం బాగుంది. నేలలో నత్రజని కొంచెం తక్కువగా ఉంది కానీ తేమ స్థాయిలు గోధుమలకు సరైనవి.",
        yellowRustAlert: "15 కిమీ లోపల పసుపు కుంకుమ తెగులు (Yellow Rust) కనబడింది",
        protectCrops: "మీ గోధుమ పంటను ఇప్పుడే రక్షించండి.",
        heatwaveAdvisory: "వడగాల్పుల హెచ్చరిక జారీ చేయబడింది",
        increaseIrrigation: "నీటి పారుదల ఫ్రీక్వెన్సీని 20% పెంచండి.",
        newSeasonQ: "కొత్త విత్తే కాలమా?",
        newSeasonDesc: "మీ ఖచ్చితమైన పరిస్థితుల ఆధారంగా అత్యంత లాభదాయకమైన పంటను కనుగొనడానికి మా AI- ఆధారిత పంట సిఫార్సు మోడల్‌ను అమలు చేయండి.",
        predictBestCrop: "ఇప్పుడే ఉత్తమ పంటను అంచనా వేయండి",
        checkedMarketPrice: "మార్కెట్ ధర తనిఖీ చేయబడింది",
        wheatPriceIncreased: "గోధుమ ధరలు ₹150 పెరిగాయి",
        ranCropPred: "పంట అంచనా వేయబడింది",
        cottonMatch: "సిఫార్సు చేయబడింది: పత్తి (88% సరిపోలిక)",
        weatherAlert: "వాతావరణ హెచ్చరిక",
        heavyRainfall: "రేపు భారీ వర్షం కురిసే అవకాశం ఉంది",
        regionalDiseaseRisks: "ప్రాంతీయ వ్యాధి ప్రమాదాలు",
        criticalAlerts: "సమీపంలో కీలకమైన హెచ్చరికలు",
        recentHistory: "ఇటీవలి చరిత్ర",
        viewAll: "అన్నీ చూడండి",
        aiInsight: "AI అంతర్దృష్టి",
        applyUrea: "గరిష్ట దిగుబడి కోసం తదుపరి 48 గంటల్లో యూరియాను వేయండి.",
        climateIntel: "శీతోష్ణస్థితి సమాచారం",
        tempRainMonitor: "ఉష్ణోగ్రత & వర్షపాత పర్యవేక్షణ",
        optimalForSeason: "ప్రస్తుత సీజన్‌కు అనువైనది",
        precisionSensorData: "ఖచ్చితమైన సెన్సార్ డేటా",
        trackLiveTrends: "ప్రత్యక్ష పోకడలను ట్రాక్ చేయండి",
        govtSchemes: "ప్రభుత్వ పథకాలు",
        schemesTitle: "ప్రభుత్వ పథకాలు & రాయితీలు",
        schemesDesc: "మీ వ్యవసాయ అభివృద్ధి మరియు ఆర్థిక స్థిరత్వానికి తోడ్పడేలా రూపొందించిన కేంద్ర మరియు రాష్ట్ర ప్రభుత్వ పథకాలను కనుగొనండి మరియు దరఖాస్తు చేసుకోండి.",
        searchSchemes: "పథకాలు, కీవర్డ్‌లు లేదా ప్రయోజనాల కోసం వెతకండి...",
        allCategories: "అన్ని రకాలు",
        keyBenefit: "ముఖ్య ప్రయోజనం",
        eligibility: "అర్హత",
        viewDetails: "వివరాలు చూడండి & దరఖాస్తు చేసుకోండి",
        noSchemes: "ఎటువంటి పథకాలు కనుగొనబడలేదు",
        adjustSearch: "మీ శోధన లేదా ఫిల్టర్లను సర్దుబాటు చేసి ప్రయత్నించండి.",
        activeStatus: "అందుబాటులో ఉంది",
        yieldTitle: "దిగుబడి అంచనా",
        yieldDesc: "పొలం పారామితులు మరియు చారిత్రక పోకడల ఆధారంగా మీ పంట దిగుబడిని అంచనా వేయండి.",
        landArea: "భూమి విస్తీర్ణం (హెక్టార్లలో)",
        cropType: "పంట రకం",
        soilType: "నేల రకం",
        croppingSeason: "పంట కాలం",
        calculateYield: "దిగుబడి సామర్థ్యాన్ని విశ్లేషించండి",
        calculatingYield: "దిగుబడిని లెక్కించుతోంది...",
        processingData: "చారిత్రక డేటాను ప్రాసెస్ చేస్తోంది",
        aiProcessingDesc: "మా AI మీ పారామితులను ప్రాంతీయ దిగుబడి బెంచ్ మార్క్‌లతో సరిపోల్చుతోంది...",
        awaitingYieldParams: "పారామితుల కోసం ఎదురు చూస్తున్నాం",
        awaitingParamsDesc: "మీ పొలం వివరాలను పూరించండి మరియు అంచనా వేసిన దిగుబడిని విశ్లేషించండి.",
        yieldResult: "అంచనా ఫలితం",
        estHarvest: "అంచనా వేసిన మొత్తం దిగుబడి",
        potentialValue: "సంభావ్య విలువ",
        estMSP: "ప్రస్తుత MSP వద్ద అంచనా",
        efficiencyScore: "సామర్థ్య స్కోరు",
        maxStrategy: "గరిష్ట వ్యూహం",
        exportReport: "నివేదికను డౌన్‌లోడ్ చేయండి",
        downloadPDF: "PDF డౌన్‌లోడ్ చేయండి",
        dataUpdated: "డేటా అప్‌డేట్ చేయబడింది",
        minAgo: "నిమిషం క్రితం",
        irrigationTitle: "స్మార్ట్ నీటిపారుదల ప్రణాళికాదారుడు",
        irrigationDesc: "AI నేల-తేమ విశ్లేషణ మరియు ఆవిరి రేట్ల ఆధారంగా ఖచ్చితమైన నీటిపారుదల.",
        nextWatering: "తదుపరి షెడ్యూల్ చేసిన ఈవెంట్",
        targetVolume: "లక్ష్యం వాల్యూమ్",
        systemOnline: "సిస్టమ్ స్థితి: ఆన్‌లైన్",
        evaporation: "ఆవిరి",
        windSpeed: "గాలి వేగం",
        automation: "ఆటోమేషన్",
        manualOverride: "మాన్యువల్ ఓవర్‌రైడ్ ప్రారంభం",
        upcomingSchedule: "రాబోయే షెడ్యూల్",
        lowRainWarning: "తక్కువ వర్షపాతం హెచ్చరిక",
        rainAdjustDesc: "షెడ్యూల్ సర్దుబాటు చేయబడింది: వచ్చే వారం +15% వాల్యూమ్ అవసరం.",
        pumpEfficiency: "పంపు సామర్థ్యం",
        maintenanceDue: "నిర్వహణ గడువు",
        days: "రోజులు",
        marketTitle: "మార్కెట్ ధర సమాచారం",
        marketDesc: "మీ పంటల కోసం ప్రత్యక్ష మండి ధరలు మరియు భవిష్యత్ పోకడలు.",
        priceAlerts: "ధర హెచ్చరికలు",
        mandiTrend: "మండి ధరల సరళి",
        perQuintal: "క్వింటాల్‌కు (100 కిలోలు)",
        marketSearch: "మార్కెట్ శోధన",
        searchCommodity: "వస్తువును శోధించండి...",
        topTrending: "టాప్ ట్రెండింగ్",
        noResults: "ఎటువంటి ఫలితాలు కనుగొనబడలేదు.",
        exportPotential: "ఎగుమతి సంభావ్యత",
        organicCottonDemand: "ఆర్గానిక్ కాటన్ కోసం అంతర్జాతీయ డిమాండ్ 15% పెరిగింది. మీ ROI పెంచడానికి ధృవీకరణను పరిగణించండి.",
        readInsights: "వివరాలను చదవండి",
        diseaseTitle: "AI రోగ గుర్తింపు",
        diseaseDesc: "తెగుళ్లు, శిలీంధ్రాలు లేదా పోషకాహార లోపాల ప్రారంభ సంకేతాల కోసం మీ పంటను స్కాన్ చేయండి.",
        selectCropDet: "విశ్లేషణ కోసం పంటను ఎంచుకోండి",
        uploadPhoto: "ఫోటోను అప్‌లోడ్ చేయండి",
        uploadDesc: "ప్రభావితమైన ఆకు లేదా కాండం యొక్క స్పష్టమైన చిత్రాన్ని తీయండి.",
        analyzingDisease: "నమూనాను విశ్లేషిస్తోంది...",
        aiScanning: "40+ సాధారణ పంట వ్యాధికారక క్రిముల కోసం AI స్కాన్ చేస్తోంది...",
        awaitingUpload: "చిత్రం కోసం ఎదురు చూస్తున్నాం",
        awaitingUploadDesc: "AI రోగనిర్ధారణ ప్రక్రియను ప్రారంభించడానికి మీ పంట ఫోటోను అప్‌లోడ్ చేయండి లేదా తీయండి.",
        diagnosis: "AI రోగనిర్ధారణ",
        confidenceDisease: "విశ్వాసం",
        treatment: "సిఫార్సు చేసిన చికిత్స",
        prevention: "నివారణ చిట్కా",
        bookConsult: "నిపుణుల సంప్రదింపులను బుక్ చేయండి",
        alertsTitle: "ఇటీవలి రోగ హెచ్చరికలు",
        alertsDesc: "ప్రాంతీయ వ్యాధి వ్యాప్తి నోటిఫికేషన్లు మరియు నివారణ సలహాలు.",
        riskLevel: "ప్రమాద స్థాయి",
        affectedCrops: "ప్రభావిత పంటలు",
        advisory: "సలహా",
        saveChanges: "మార్పులను సేవ్ చేయండి",
        applyNow: "ఇప్పుడే దరఖాస్తు చేసుకోండి"
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'English');

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
